import logging
from pyspark.sql import SparkSession
from src.services.envs import EnvConfig

logger = logging.getLogger(__name__)

def _build_config(env: EnvConfig) -> dict[str, str]:
    return {
        "gold_dim_customers_table": f"{env.catalog}.{env.schemas['gold']}.g_dim_customers",
        "gold_dim_plan_catalog_table": f"{env.catalog}.{env.schemas['gold']}.g_dim_plan_catalog",
        "gold_fact_usage_daily_table": f"{env.catalog}.{env.schemas['gold']}.g_fact_usage_daily",
        "gold_fact_invoices_table": f"{env.catalog}.{env.schemas['gold']}.g_fact_stripe_invoices",
        "gold_fact_subscription_items_table": f"{env.catalog}.{env.schemas['gold']}.g_fact_stripe_subscription_items",
        "gold_dim_subscriptions_table": f"{env.catalog}.{env.schemas['gold']}.g_dim_stripe_subscriptions",


        "gold_dim_customers_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_dim_customers",
        "gold_dim_plan_catalog_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_dim_plan_catalog",
        "gold_fact_usage_daily_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_fact_usage_daily",
        "gold_fact_invoices_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_fact_stripe_invoices",
        "gold_fact_subscription_items_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_fact_stripe_subscription_items",
        "gold_dim_subscriptions_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_dim_stripe_subscriptions",
    }


def bootstrap_gold(spark: SparkSession, env: EnvConfig) -> None:

    cfg = _build_config(env=env)

    logger.info("Creating/validating dim_customers in schema %s", f"{env.catalog}.{env.schemas['gold']}")

    spark.sql(f"""
            CREATE TABLE IF NOT EXISTS {cfg["gold_dim_customers_table"]} (
                customer_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,

                customer_business_key STRING NOT NULL,

                account_id STRING,
                stripe_customer_id STRING,

                customer_name STRING,
                email STRING,
                plan_code STRING,
                segment STRING,
                country_code STRING,
                region STRING,

                account_created_date DATE,
                account_status STRING,
                churned_date DATE,
                account_source_system STRING,
                account_snapshot_date DATE,

                stripe_currency STRING,
                stripe_description STRING,
                stripe_order_id STRING,
                stripe_customer_created_ts TIMESTAMP,
                is_delinquent BOOLEAN,
                is_livemode BOOLEAN,
                stripe_api_extracted_ts TIMESTAMP,

                account_silver_effective_start_ts TIMESTAMP,
                account_silver_effective_end_ts TIMESTAMP,
                stripe_silver_effective_start_ts TIMESTAMP,
                stripe_silver_effective_end_ts TIMESTAMP,

                etl_run_id STRING,
                gold_processed_ts TIMESTAMP,
                gold_processed_date DATE,
                record_hash STRING
            )
            USING DELTA
            LOCATION '{cfg["gold_dim_customers_path"]}'
            """)
    logger.info("Ensure table exists: %s", cfg["gold_dim_customers_table"])


    spark.sql(f"""
                CREATE TABLE IF NOT EXISTS {cfg['gold_dim_plan_catalog_table']} (
                    plan_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,

                    plan_business_key STRING NOT NULL,

                    plan_code STRING,
                    plan_name STRING,

                    monthly_price_usd BIGINT,
                    seats_included BIGINT,
                    max_units_per_month BIGINT,

                    currency STRING,
                    billing_period STRING,

                    effective_from DATE,
                    effective_to DATE,
                    source_is_current BOOLEAN,
                    price_version STRING,

                    silver_effective_start_ts TIMESTAMP,
                    silver_effective_end_ts TIMESTAMP,

                    etl_run_id STRING,
                    gold_processed_ts TIMESTAMP,
                    gold_processed_date DATE,
                    record_hash STRING
                )
                USING DELTA
                LOCATION '{cfg["gold_dim_plan_catalog_path"]}'
                """)
    logger.info("Ensure table exists: %s", cfg["gold_dim_plan_catalog_table"])


    spark.sql(f"""
                CREATE TABLE IF NOT EXISTS {cfg["gold_fact_usage_daily_table"]} (
                    usage_business_key STRING NOT NULL,
                    usage_id STRING,

                    customer_sk BIGINT,
                    plan_sk BIGINT,

                    account_id STRING,
                    stripe_customer_id STRING,
                    plan_code STRING,

                    event_ts TIMESTAMP,
                    usage_date DATE,
                    feature_code STRING,

                    active_users BIGINT,
                    units_raw BIGINT,

                    source_system STRING,
                    batch_id STRING,

                    etl_run_id STRING,
                    gold_processed_ts TIMESTAMP,
                    gold_processed_date DATE,
                    record_hash STRING
                )
                USING DELTA
                LOCATION '{cfg["gold_fact_usage_daily_path"]}'
                """)
    logger.info("Ensure table exists: %s", cfg["gold_fact_usage_daily_table"])


    spark.sql(f"""
                CREATE TABLE IF NOT EXISTS {cfg["gold_fact_invoices_table"]} (
                    invoice_business_key STRING NOT NULL,
                    invoice_id STRING,

                    subscription_sk BIGINT,
                    customer_sk BIGINT,
                    plan_sk BIGINT,

                    stripe_customer_id STRING,
                    subscription_id STRING,
                    account_id STRING,
                    plan_code STRING,

                    invoice_status STRING,
                    collection_method STRING,
                    currency STRING,
                    invoice_number STRING,

                    amount_due BIGINT,
                    amount_paid BIGINT,
                    amount_remaining BIGINT,
                    subtotal BIGINT,
                    subtotal_excluding_tax BIGINT,
                    total BIGINT,

                    attempt_count BIGINT,
                    is_attempted BOOLEAN,
                    is_livemode BOOLEAN,
                    auto_advance BOOLEAN,

                    created_ts TIMESTAMP,
                    due_date_ts TIMESTAMP,
                    period_start_ts TIMESTAMP,
                    period_end_ts TIMESTAMP,
                    status_finalized_ts TIMESTAMP,
                    status_paid_ts TIMESTAMP,
                    status_voided_ts TIMESTAMP,
                    status_marked_uncollectible_ts TIMESTAMP,
                    api_extracted_ts TIMESTAMP,

                    etl_run_id STRING,
                    gold_processed_ts TIMESTAMP,
                    gold_processed_date DATE,
                    record_hash STRING
                )
                USING DELTA
                LOCATION '{cfg["gold_fact_invoices_path"]}'
                """)
    logger.info("Ensure table exists: %s", cfg["gold_fact_invoices_table"])


    spark.sql(f"""
                CREATE TABLE IF NOT EXISTS {cfg["gold_fact_subscription_items_table"]} (
                    subscription_item_business_key STRING NOT NULL,
                    subscription_item_id STRING,

                    subscription_sk BIGINT,
                    customer_sk BIGINT,
                    plan_sk BIGINT,

                    subscription_id STRING,
                    stripe_customer_id STRING,
                    account_id STRING,
                    plan_code STRING,

                    price_id STRING,
                    product_id STRING,
                    item_currency STRING,
                    billing_interval STRING,
                    price_type STRING,
                    usage_type STRING,

                    quantity BIGINT,
                    unit_amount BIGINT,

                    item_created_ts TIMESTAMP,
                    item_current_period_start_ts TIMESTAMP,
                    item_current_period_end_ts TIMESTAMP,
                    api_extracted_ts TIMESTAMP,

                    etl_run_id STRING,
                    gold_processed_ts TIMESTAMP,
                    gold_processed_date DATE,
                    record_hash STRING
                )
                USING DELTA
                LOCATION '{cfg["gold_fact_subscription_items_path"]}'
                """)
    logger.info("Ensure table exists: %s", cfg["gold_fact_subscription_items_table"])


    spark.sql(f"""
                CREATE TABLE IF NOT EXISTS {cfg["gold_dim_subscriptions_table"]} (
                    subscription_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,

                    subscription_business_key STRING NOT NULL,
                    subscription_id STRING,

                    stripe_customer_id STRING,

                    subscription_status STRING,
                    collection_method STRING,
                    currency STRING,
                    latest_invoice_id STRING,

                    created_ts TIMESTAMP,
                    start_date_ts TIMESTAMP,
                    billing_cycle_anchor_ts TIMESTAMP,
                    cancel_at_ts TIMESTAMP,
                    canceled_at_ts TIMESTAMP,
                    ended_at_ts TIMESTAMP,
                    trial_start_ts TIMESTAMP,
                    trial_end_ts TIMESTAMP,

                    cancel_at_period_end BOOLEAN,
                    is_livemode BOOLEAN,
                    api_extracted_ts TIMESTAMP,

                    silver_effective_start_ts TIMESTAMP,
                    silver_effective_end_ts TIMESTAMP,

                    etl_run_id STRING,
                    gold_processed_ts TIMESTAMP,
                    gold_processed_date DATE,
                    record_hash STRING
                )
                USING DELTA
                LOCATION '{cfg["gold_dim_subscriptions_path"]}'
                """)
    logger.info("Ensure table exists: %s", cfg["gold_dim_subscriptions_table"])