import logging
from pyspark.sql import SparkSession
from src.services.envs import EnvConfig

logger = logging.getLogger(__name__)

def _build_config(env: EnvConfig) -> dict[str, str]:
    return {
        "gold_table": f"{env.catalog}.{env.schemas['gold']}.g_dim_customer",

        "gold_path": f"{env.gold_base_path}/{env.catalog}/{env.schemas['gold']}/g_dim_customer",
    }


def bootstrap_dim_customer(spark: SparkSession, env: EnvConfig) -> None:

    cfg = _build_config(env=env)

    logger.info("Creating/validating dim_customer in schema %s", f"{env.catalog}.{env.schemas['gold']}")

    spark.sql(f"""
            CREATE TABLE IF NOT EXISTS {cfg["gold_table"]} (
                customer_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,

                customer_business_key STRING NOT NULL,

                account_master_snapshot_sk BIGINT,
                stripe_customers_sk BIGINT,

                account_id STRING,
                stripe_customer_id STRING,

                customer_name STRING,
                email STRING,
                plan_code STRING,
                segment STRING,
                country_code STRING,
                region STRING,

                account_created_date DATE,
                account_status STRING,
                churned_date DATE,
                account_source_system STRING,
                account_snapshot_date DATE,

                stripe_currency STRING,
                stripe_description STRING,
                stripe_order_id STRING,
                stripe_customer_created_ts TIMESTAMP,
                is_delinquent BOOLEAN,
                is_livemode BOOLEAN,
                stripe_api_extracted_ts TIMESTAMP,

                account_silver_effective_start_ts TIMESTAMP,
                account_silver_effective_end_ts TIMESTAMP,
                stripe_silver_effective_start_ts TIMESTAMP,
                stripe_silver_effective_end_ts TIMESTAMP,

                etl_run_id STRING,
                gold_processed_ts TIMESTAMP,
                gold_processed_date DATE,
                record_hash STRING
            )
            USING DELTA
            LOCATION '{cfg["gold_path"]}'
            """)